implement method to get classes associated with slot
linkml/linkml-runtime pull request #197
Opened 2022-08-05 17:35 UTC by sujaypatil96

Implement a method to get all classes that use a given slot.

2022-08-05 20:11 UTC, sujaypatil96 commented on linkml_runtime/utils/schemaview.py
> +from unicodedata import name
Remove.

2022-08-05 20:23 UTC, turbomam commented
A slot can be used legally within a class if
- the class mentions is in it's `slots`
- the class mentions it in it's `attributes`
- the class mentions it in `slot_usage` without being mentioned in `slots` (which is allowed but warned against)
- the class has a ancestor class that uses the slot

we could create a single method with flags for each case, returning a single unqualified list.

if any of those conditions are difficult to process, that case could be omitted for now (good idea, @kevinschaper)

2022-08-08 18:16 UTC, sujaypatil96 commented
Thank you for breaking up the various possible use cases in which we can determine the classes associated with a slot.

* when `direct` is set to True, we are computing the first use case, i.e., slots mentioned in `slots` property of a class
* when `induced` is True, we are computing the second and third use cases together, slots mentioned under `attributes` and `slot_usage` properties on a class

2022-08-08 18:18 UTC, turbomam commented
> @turbomam: thank you for breaking up the various possible use cases in which we can determine the classes associated with a slot.
> 
> * when `direct` is set to True, we are computing the first use case, i.e., slots mentioned in `slots` property of a class
> * when `induced` is True, we are computing the second and third use cases together, slots mentioned under `attributes` and `slot_usage` properties on a class

OK, does that mean that slots asserted by ancestors won't appear in this first solution? We should come up with some test cases.

2022-08-09 16:12 UTC, cmungall commented on linkml_runtime/utils/schemaview.py
> +            if direct == True:
replace with `if direct:`

2022-08-09 16:14 UTC, cmungall commented on linkml_runtime/utils/schemaview.py
> +        :param direct: list all slots directly in the domain of a class, defaults to True
consider if you really need two boolean parameters here. If both are specified, you raise an error (good). But if neither are specified (which is the default) then this returns an empty list.

if you look at other methods you will see it's more idiomatic to have the method always return direct and to have a single boolean param to determine whether this should be supplemented with induced

2022-08-09 16:15 UTC, cmungall requested changes
thanks!

note there is a method for getting usages which is a superset of this, but it's useful to have something like this

2022-08-11 01:16 UTC, cmungall approved these changes

2022-08-11 16:21 UTC, merged