SchemaView initialization from a PosixPath
linkml/linkml-runtime pull request #249
Opened 2023-02-18 21:06 UTC by joeflack4

Updates
```
- Update: UX: SchemaView: Creating a new instance now accepts a PosixPath rather than just a string representation of a file path.
```

2023-02-18 21:07 UTC, joeflack4 reviewed
Addresses:
- https://github.com/linkml/linkml/issues/1056

2023-02-18 21:07 UTC, joeflack4 commented on linkml_runtime/utils/schemaview.py
> +        if isinstance(schema, str) or isinstance(schema, PosixPath):
I had 3 different proposed ways to do this in [this issue](https://github.com/linkml/linkml/issues/1056), but I felt like this way was even simpler than those.

2023-02-21 15:47 UTC, sierra-moxon approved these changes

2023-02-21 15:47 UTC, sierra-moxon commented
@joeflack4 - looks great!  if possible, could you add or edit a test to take advantage of the new support for PosixPath?

2023-02-21 19:26 UTC, cmungall requested changes
Thanks!

I suggest generalizing this to work with other paths - see https://docs.python.org/3/library/pathlib.html - unless there is a reason to restrict?

2023-02-25 00:07 UTC, merged

2023-02-25 19:29 UTC, joeflack4 commented
@cmungall I was going to look at these requests this weekend. Thanks for handling! I see as well the need to convert it to a string as well within `__init__`, thanks for handling that.