Enable passing a converter to RDFLib dumper
linkml/linkml-runtime pull request #278
Opened 2023-09-08 10:39 UTC by cthoyt

This pull request extends the type signature of functions in the RDFlib loader and dumper to allow passing a `curies.Converter` instead of a simple prefix map (if desired). The bidirected map is extracted from the converter and the respective loading/dumping procedures are not modified.

2023-09-08 20:46 UTC, cmungall approved these changes

2023-09-08 20:57 UTC, cmungall requested changes
Would you be up for making a test? If not one of us can handle it

2023-09-09 06:24 UTC, cthoyt commented
@cmungall done

2023-09-13 22:31 UTC, cmungall commented
Fixes https://github.com/linkml/linkml/issues/1619

2023-09-14 20:34 UTC, cmungall approved these changes

2023-09-26 11:14 UTC, cthoyt commented
@pkalita-lbl is there anything else needed for merge?

2023-09-26 16:15 UTC, pkalita-lbl commented
Looks good to me

2023-09-26 16:15 UTC, merged