BF: Fix bug and other improvement in `SchemaBuilder.add_class()`
linkml/linkml-runtime pull request #338
Opened 2024-08-27 00:27 UTC by candleindark

This PR does the following.

1. Remove the use of `kwargs` in setting `cls` if it's given as an argument as a `ClassDefinition` object
2. Correct detection of duplicating classes
3. Ensure `slots` is correct type when `use_attributes=True`

Point 1 is included in this PR because the following lines are unneeded for the cases in which `cls` is given as a `dict` or `str` and are inconsistent with the behavior of `SchemaBuilder.add_slot()` and `SchemaBuilder.add_enum()`. In both `SchemaBuilder.add_slot()` and `SchemaBuilder.add_enum()`, if the first argument is of the target type, `SlotDefinition` and `EnumDefinition` respectively, `kwargs` is ignored.

https://github.com/linkml/linkml-runtime/blob/9fd5a3e374a1d1820da07a0e3d165b8f667033f4/linkml_runtime/utils/schema_builder.py#L101-L102

2024-08-27 16:35 UTC, yarikoptic commented
If you could add a test which would demonstrate (fail) the issue without this fix, that would be great.

2024-08-30 02:51 UTC, cmungall requested changes
Thanks @candleindark - do you think you can add the test as @yarikoptic suggests?

2024-09-03 16:17 UTC, candleindark commented
> Thanks @candleindark - do you think you can add the test as @yarikoptic suggests?

I think I can do that. Any suggestion in where is the best place to put these tests.

2024-09-05 20:26 UTC, cmungall commented
Hmm, I thought we had a test_schemabuilder here https://github.com/linkml/linkml-runtime/tree/main/tests/test_utils but it seems not... if you can start one that would be great. We favor simple pytest style tests.

2024-10-01 15:04 UTC, cmungall approved these changes

2025-02-13 02:48 UTC, merged