Linkml issue 497: Inherited class slots are not reflecting the correct range in the python and markdown files
linkml/linkml-runtime pull request #81
Opened 2021-12-03 20:18 UTC by wdduncan

Fixes https://github.com/linkml/linkml/issues/497

@cmungall The unit test passes. However, if you look a the generated python file `linkml-runtime/tests/test_issues/input/linkml_issue_497.py`, you will see that the `has_input` attribute of `OmicsProcessing` is of type `NamedThing`:

```python
@dataclass
class OmicsProcessing(BiosampleProcessing):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = URIRef("https://example.com/test-inherited-ranges/OmicsProcessing")
    class_class_curie: ClassVar[str] = None
    class_name: ClassVar[str] = "omics processing"
    class_model_uri: ClassVar[URIRef] = URIRef("https://example.com/test-inherited-ranges/OmicsProcessing")

    has_input: Optional[Union[Union[dict, NamedThing], List[Union[dict, NamedThing]]]] = empty_list()
...
```
I did some playing around, and found out that if I remove/comment out the `has input` slot from the `omics processing` class in the yaml file, and include the `slot_usage` like so:
```yaml
    slot_usage:
        has input:
         required: true    
```
the type of the `has_input` attribute in the python file will be `Biosample`

2021-12-03 20:21 UTC, cmungall requested changes
I think you meant to put in linkml

however it is still a good schemaview test - you can remove the generated py file and we can keep this test

2021-12-04 00:22 UTC, wdduncan commented
@cmungall I added a hacky check for the range of `has input` using a regex on the python file.

2021-12-04 19:40 UTC, cmungall commented on tests/test_issues/test_linkml_issue_497.py
> +      with open(env.input_path('linkml_issue_497.py')) as f:
It looks like you are testing a statically checked in file. If you are intending to test PythonGenerator, then the generators are in the linkml repo.

2021-12-06 21:13 UTC, wdduncan commented
Closing this PR, and moving to the LinkML repo.

2021-12-06 21:13 UTC, closed without merging